services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: camocam-be:latest
    container_name: camocam-be
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - hf-models:/models
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  hf-models:
